export default [
	{
		creationDate: new Date(),
		description: 'Todo1 - #1',
		completed: false,
		important: false,
		id: 54321,
		tags: ['today'],
	},
	{
		creationDate: new Date(),
		description: 'Todo1 - #2',
		completed: true,
		important: false,
		id: 98765,
		tags: ['today', 'completed'],
	},
	{
		creationDate: new Date(),
		description: 'Todo1 - #3',
		completed: true,
		important: false,
		id: 24680,
		tags: ['today', 'completed'],
	},
	{
		creationDate: new Date(),
		description: 'Todo1 - #4',
		completed: true,
		important: false,
		id: 13579,
		tags: ['completed'],
	},
	{
		creationDate: new Date(),
		description: 'Todo1 - #5',
		completed: false,
		important: true,
		id: 86420,
		tags: ['important', 'today'],
	},
	{
		creationDate: new Date(),
		description: 'Todo1 - #6',
		completed: false,
		important: true,
		id: 77777,
		tags: ['today', 'important'],
	},
	{
		creationDate: new Date(),
		description: 'Todo1 - #7',
		completed: false,
		important: true,
		id: 22222,
		tags: ['important'],
	},
	{
		creationDate: new Date(),
		description: 'Todo1 - #8',
		completed: false,
		important: true,
		id: 44444,
		tags: ['important', 'newList'],
	},
	{
		creationDate: new Date(),
		description: 'Todo1 - #9',
		completed: false,
		important: false,
		id: 88888,
		tags: [],
	},
	{
		creationDate: new Date(),
		description: 'Todo1 - #10',
		completed: false,
		important: false,
		id: 99999,
		tags: [],
	},
];
